/**
 * AFS Advocates — UI Hints
 * Tooltip/placeholder text for every document field in the ArgumentBuilder.
 * Keyed by field ID — component looks up by id to populate placeholders.
 */

export const HINTS: Record<string, string> = {
  // ── Pleadings ──────────────────────────────────────────────────────────────
  writ:             'Writ of Summons — the originating process that commences the action.',
  soc:              'Statement of Claim — every material fact pleaded with particularity.',
  witness_proofs:   'Witness proofs — brief, factual, first-person statements for each witness.',
  pre_action:       'Pre-action checklist — every condition precedent verified before filing.',
  timeline:         'Litigation timeline — key dates from cause of action through anticipated judgment.',
  sod:              'Statement of Defence — specific denials, traverse every material allegation.',
  prelim_obj:       'Preliminary objections — jurisdiction, limitation, competence issues raised upfront.',
  defence_check:    'Defence checklist — every procedural and evidential issue before filing.',
  reply:            "Reply to Statement of Defence — the Claimant's response to new matters raised.",
  joinder:          'Joinder of Issue — a general joinder closes the pleadings on unanswered paragraphs.',
  def_counterclaim: 'Defence to the Counterclaim — treat it like their originating claim, traverse every paragraph.',
  cc_stmt:          'Full Statement of Counterclaim — every element pleaded, every relief endorsed.',
  cc_relief:        'Formal counterclaim prayers — drafted in court language, nothing left on the table.',
  cc_defence:       'Defence to the Counterclaim — if the Claimant files one, here is how to respond.',
  tp_notice:        'Third-Party Notice in proper court form — joining the third party to the existing proceedings.',
  tp_claim:         'Statement of Claim against the Third Party — same standard as an originating claim.',
  contribution:     'Contribution or Indemnity — why the third party must bear all or part of the liability.',
  // ── Trial ──────────────────────────────────────────────────────────────────
  no_case_sub:      'Submission of No Case to Answer — the Claimant has failed to make out a prima facie case on the following elements.',
  nc_rebuttal:      "Claimant's rebuttal to the no-case submission — argue the prima facie case has been made out.",
  nc_analysis:      'Ruling analysis — what the court is likely to do and how to respond to either outcome.',
  amend_app:        'Application to amend the pleadings during trial — necessity, no prejudice, justice of the case.',
  amended_plea:     'The amended pleading itself — new paragraphs clearly flagged, complete and self-standing.',
  opp_amend:        'Opposition to amendment — prejudice, delay, bad faith, tactical amendment at this stage.',
  // ── Interlocutory ──────────────────────────────────────────────────────────
  motion_paper:     'Motion paper in proper form — relief sought, grounds, supporting processes listed.',
  supp_aff:         'Supporting affidavit — the facts exhibiting every document relied on.',
  written_addr:     'Written address — the law, the arguments, the conclusion in proper form.',
  counter_strike:   "Anticipate the respondent's counter — the weakest points of your application.",
  weakness_radar:   "Every vulnerability in your application — what they'll attack and how to address it.",
  counter_aff:      'Counter-affidavit — specific denials of the applicant\'s affidavit, paragraph by paragraph.',
  addr_opp:         'Written address in opposition — why the application should fail.',
  reply_law:        'Reply on points of law — responding to new legal arguments in the address in opposition.',
  // ── Appeal ─────────────────────────────────────────────────────────────────
  grounds:          'Grounds of appeal — specific errors of law or fact, numbered, concise.',
  issues:           'Issues for determination — distilled from the grounds, properly formulated.',
  appell_brief:     "Appellant's brief of argument — arguments on each issue, citing authorities.",
  reply_brief:      "Reply brief — responding specifically to new points in the respondent's brief.",
  prelim_obj_app:   "Preliminary objection to the appeal — incompetence of grounds, failure to seek leave.",
  resp_issues:      "Respondent's issues for determination — formulated to defeat the appeal.",
  resp_brief:       "Respondent's brief — sustaining the judgment, answering appellant's arguments.",
  cross_appeal:     "Cross-appeal — where the respondent also appeals aspects of the judgment.",
  // ── Specialised ────────────────────────────────────────────────────────────
  bail_app:         'Bail application in proper form — prayers, grounds, conditions offered.',
  bail_aff:         "Affidavit in support of bail — accused's ties, flight risk assessment, proposed sureties.",
  bail_addr:        'Written address in support of bail — legal principles on bail, discretion factors.',
  bail_opp:         "Prosecution's opposition to bail — danger to society, flight risk, offence gravity.",
  order_nisi:       'Application for Garnishee Order Nisi — judgment details, the garnishee, amount.',
  order_abs:        'Application to make the order absolute — no cause shown by the garnishee.',
  garnishee_opp:    "Garnishee's opposition — the account is empty, funds are disputed, third-party claims.",
  fifa_writ:        "Writ of Fieri Facias — authorising the Sheriff to levy execution on the judgment debtor's goods.",
  enf_app:          "Enforcement application — the nature of the judgment, the debtor's non-compliance, the relief sought.",
  jd_summons:       'Judgment Debtor Summons — compelling the debtor to appear and disclose assets.',
  contempt_motion:  'Motion to commit for contempt — the order, the knowledge, the disobedience.',
  contempt_aff:     'Affidavit of disobedience — who breached what order, when, how, and what the evidence is.',
  contempt_addr:    'Written address — why this is contempt, what sanction the court should impose.',
  contempt_resp:    "Contemnor's response — compliance efforts, inability to comply, mitigation.",
  petition:         'Full Election Petition — parties, election details, grounds, material facts, relief.',
  pet_addr:         "Petitioner's written address — the irregularities, the law, the remedy.",
  resp_reply_ep:    "Respondent's reply — election was conducted substantially in accordance with the law.",
  phr_report:       'Pre-Hearing Report — issues agreed, issues in dispute, witnesses, documents.',
  ep_witnesses:     'Witness proofs — lay witnesses and subpoenaed electoral officials.',
  wu_petition:      'Winding-Up Petition — the company, the ground, the debt/evidence.',
  wu_aff:           'Supporting affidavit — the debt, the demand, the failure to pay, the presumption of insolvency.',
  wu_addr:          'Written address — the legal grounds for winding up, the court\'s duty to make the order.',
  wu_opp:           'Opposition to winding-up — the company is solvent, the debt is disputed, the petition is an abuse.',
  fr_motion:        'Originating Motion for Fundamental Rights Enforcement — the rights, the breach, the respondents.',
  fr_aff:           'Affidavit in support — the facts establishing the infringement of fundamental rights.',
  fr_addr:          'Written address — the rights violated, the constitutional provisions, the remedies available.',
  fr_resp:          "Respondent's response — state action was lawful, applicable derogation provisions.",
  arb_stmt:         'Statement of Case for arbitration — claims, factual matrix, legal basis, relief sought.',
  arb_def:          'Defence and Counterclaim in arbitration — traversal, positive case, counterclaim if any.',
  arb_reply:        "Claimant's reply to defence — closing the issues, responding to counterclaim.",
  arb_bundle:       'Hearing bundle note — document list, agreed facts, issues, witness schedule.',
  arb_enf:          'Award enforcement application — Arbitration Act, recognition, enforcement steps.',
  // ── Settlement ─────────────────────────────────────────────────────────────
  cj_terms:         'Terms of Settlement — the agreed terms that will form the basis of the consent judgment.',
  cj_draft:         'Consent Judgment in proper court form — endorsed by all parties, ready for sealing.',
  cj_enf:           'Enforcement clause — making the consent judgment enforceable without further proceedings.',
  ds_recitals:      'Recitals — the background, the dispute, the agreement to settle.',
  ds_terms:         'Terms and Conditions — the full settlement terms, payment, release, confidentiality.',
  ds_full:          'Full executed Deed of Settlement — recitals, terms, warranties, execution block.',
  disc_notice:      'Notice of Discontinuance — formal notice under the Rules of Court.',
  disc_costs:       'Costs terms — agreed costs provisions accompanying the discontinuance.',
  disc_consent:     'Consent Order recording the discontinuance and any agreed terms.',
  // ── Practice Documents ─────────────────────────────────────────────────────
  ret_letter:       'Client retainer / engagement letter — the formal terms of the professional engagement.',
  fee_agree:        'Fee agreement — basis of fees, billing method, payment terms, disbursements.',
  scope_inst:       'Scope of instructions — what counsel is retained to do and not to do.',
  op_exec:          'Executive summary of the legal opinion — the answer in plain language, up front.',
  op_full:          'Full legal opinion — analysis, applicable law, conclusion, recommendations.',
  op_risks:         'Risk register — every risk rated, mitigation strategies for each.',
  strat_overview:   'Strategic overview — where we are, where we want to be, what is in the way.',
  strat_options:    'Strategic options — each option with its costs, risks, probability, and timeline.',
  strat_sequence:   'Tactical sequence — the specific steps in the order they should be taken.',
  risk_overview:    'Risk overview — the case at a glance, the top three risks.',
  risk_vuln:        'Vulnerabilities — every weakness in the case, honestly assessed.',
  risk_prob:        'Probability assessment — honest percentage, the factors driving it up and down.',
  risk_rec:         'Recommendation — what counsel recommends the client do, in plain terms.',
  demand_formal:    'Formal demand / pre-action letter — setting out the claim, demanding compliance by a date.',
  demand_final:     'Final notice — last chance before legal proceedings commence.',
  report_status:    'Case status report — where the matter stands today, in plain English for the client.',
  report_next:      'Next steps — what happens next, in what order, and approximate timeline.',
  report_client:    'Client action items — what the client must do now, specifically.',
  // ── Smart Tools ────────────────────────────────────────────────────────────
  cs_analysis:      'Comprehensive case strength analysis — probability, the key arguments, the weak points.',
  cs_vuln:          'Every vulnerability that could lose the case — ranked by impact.',
  cs_rec:           'Strategic recommendation — file, negotiate, or walk away?',
  dl_limitation:    'Limitation period analysis — when it expires, whether it has expired, any extensions.',
  dl_procedural:    'Procedural deadlines — service, exchange, filing, hearing timelines.',
  dl_appeal:        'Appeal windows — from what date, how long, whether any extension is possible.',
  sa_litigation:    'Realistic litigation outcome — probability-weighted expected outcome.',
  sa_settlement:    'Realistic settlement range — what a reasonable settlement looks like.',
  sa_rec:           'The recommendation — what your client should actually do.',
  jb_analysis:      "Analysis of this specific court's tendencies — what moves this judge.",
  jb_rewritten:     'Your argument rewritten specifically for this court and judge.',
  cr_topic:         'Nigerian cases on this legal topic — with citations, holdings, and where to find them.',
  cr_statute:       'Cases interpreting this specific statute or section — key holdings per court level.',
  cr_principle:     'Cases establishing or applying this legal principle in Nigerian courts.',
};
