/**
 * AFS Legal OS — useIntelligence Hook
 *
 * Single source of truth for reading Intelligence Engine output.
 * Every engine that needs case facts imports THIS — not raw activeCase fields.
 *
 * Returns:
 *   - intelBlock  : formatted string injected into every AI system prompt
 *   - hasIntel    : whether any intelligence data exists
 *   - counselBlock: formatted counsel instructions (if set)
 *   - fullContext : intelBlock + counselBlock combined — pass to AI calls
 *
 * Phase 3 — Scoped Intelligence
 * ──────────────────────────────
 * Pass `scope` to limit how much intelligence context is sent:
 *
 *   'facts'   → established_facts + rawFacts/intPkg header only.
 *               Use for procedural applications (extensions, adjournments,
 *               compliance checks, alerts, enforcement) where the AI only
 *               needs to know what happened, not the full legal analysis.
 *
 *   'issues'  → facts + legal_issues + disputed_areas.
 *               Use for research tasks (CaseResearch, ResearchResolver,
 *               AuthorityValidator) that need legal framing but not the
 *               full risk register or timeline.
 *
 *   'full'    → everything (default — backwards-compatible).
 *               Use for substantive drafting: arguments, briefs, addresses,
 *               cross-exam, plea, sentencing, WarRoom, AICopilot.
 *
 * Scope is applied to intelBlock only. counselBlock is always included in
 * full and issues; omitted in facts (counsel strategy is not needed for
 * procedural tasks).
 */

import type { Case } from '@/types';

interface IntelligenceData {
  rawFacts?:         string;
  intPkg?:           string;
  established_facts?: string[];
  disputed_areas?:   string[];
  legal_issues?:     string[];
  gaps_identified?:  string[];
  initial_risks?:    Array<{ risk: string; severity: string }>;
  timeline?:         Array<{ date: string; event: string; significance?: string }>;
}

export type IntelligenceScope = 'facts' | 'issues' | 'full';

export interface IntelOutput {
  /** Whether any vetted intelligence exists for this case */
  hasIntel: boolean;

  /** Structured intelligence block — inject into AI system prompts */
  intelBlock: string;

  /** Counsel instructions block — inject after intelBlock */
  counselBlock: string;

  /** Full context = intelBlock + counselBlock — use this in AI calls */
  fullContext: string;

  /** Raw intelligence data fields for components that need direct access */
  raw: IntelligenceData;
}

/**
 * Extracts and formats all intelligence from activeCase.intelligence_data
 * plus counsel instructions from activeCase.counsel_instructions.
 *
 * Usage:
 *   // Full context (default — drafting engines):
 *   const { fullContext, hasIntel } = useIntelligence(activeCase);
 *
 *   // Facts only (procedural engines):
 *   const { fullContext } = useIntelligence(activeCase, 'facts');
 *
 *   // Facts + legal issues (research engines):
 *   const { fullContext } = useIntelligence(activeCase, 'issues');
 */
export function useIntelligence(
  activeCase: Case | null,
  scope: IntelligenceScope = 'full',
): IntelOutput {
  const intel = (activeCase?.intelligence_data || {}) as IntelligenceData;
  const instructions = (activeCase as any)?.counsel_instructions as string | undefined;

  const hasIntel = !!(
    intel.intPkg ||
    intel.rawFacts ||
    (intel.established_facts?.length ?? 0) > 0 ||
    intel.digest
  );

  // ── Intelligence Block ────────────────────────────────────────────────────
  // Phase 5: When a digest exists, serve it instead of re-rendering the raw
  // arrays. Same precedence rule as intPkg over rawFacts. The digest is a
  // compressed prose summary generated by compressIntelligence() once the
  // pipeline reaches stage 5 — it is shorter than the full array expansion
  // and compounds with Phase 2 prompt caching (smaller cacheable block).
  //
  // Scope still applies to the digest path: 'facts' returns just the package
  // header + digest; 'issues' adds counsel block; 'full' is identical to
  // 'issues' for a digest (nothing further to add — it already contains
  // risks and gaps folded in by compressIntelligence).
  // ─────────────────────────────────────────────────────────────────────────
  const parts: string[] = [];

  if (hasIntel) {
    parts.push('═══════════════════════════════════════');
    parts.push('VETTED CASE INTELLIGENCE (Intelligence Engine Output)');
    parts.push('═══════════════════════════════════════');
    parts.push('Use ONLY these verified facts. Do not contradict them.');
    parts.push('Where silent, supplement from general legal knowledge but clearly distinguish.');
    parts.push('');
  }

  if (intel.digest) {
    // ── Digest path (Phase 5) — compressed prose replaces raw arrays ─────
    parts.push('── INTELLIGENCE DIGEST ──');
    parts.push(intel.digest);
    parts.push('');

    // Always include the full intPkg alongside the digest when present —
    // the digest is a compression of the arrays, not a replacement for the
    // detailed package which contains specific reasoning and authorities.
    if (intel.intPkg) {
      parts.push('── INTELLIGENCE PACKAGE ──');
      parts.push(intel.intPkg);
      parts.push('');
    }
  } else {
    // ── Raw-array path (pre-digest or digest generation pending) ─────────

    // 'facts' scope: core package + established facts only
    if (intel.intPkg) {
      parts.push('── INTELLIGENCE PACKAGE ──');
      parts.push(intel.intPkg);
      parts.push('');
    }

    if (intel.established_facts?.length) {
      parts.push('── ESTABLISHED FACTS ──');
      intel.established_facts.forEach(f => parts.push(`• ${f}`));
      parts.push('');
    }

    if (intel.rawFacts && !intel.intPkg) {
      // Only show rawFacts if no processed package yet
      parts.push('── RAW FACTS (unprocessed — treat as client narration) ──');
      parts.push(intel.rawFacts);
      parts.push('');
    }

    // 'issues' scope: adds legal framing
    if (scope === 'issues' || scope === 'full') {
      if (intel.disputed_areas?.length) {
        parts.push('── DISPUTED AREAS ──');
        intel.disputed_areas.forEach(d => parts.push(`• ${d}`));
        parts.push('');
      }

      if (intel.legal_issues?.length) {
        parts.push('── LEGAL ISSUES ──');
        intel.legal_issues.forEach(i => parts.push(`• ${i}`));
        parts.push('');
      }
    }

    // 'full' scope: adds gaps, risks, timeline
    if (scope === 'full') {
      if (intel.gaps_identified?.length) {
        parts.push('── IDENTIFIED GAPS ──');
        intel.gaps_identified.forEach(g => parts.push(`• ${g}`));
        parts.push('');
      }

      if (intel.initial_risks?.length) {
        parts.push('── RISK REGISTER ──');
        intel.initial_risks.forEach(r => parts.push(`• [${r.severity}] ${r.risk}`));
        parts.push('');
      }
    }
  }

  const intelBlock = parts.join('\n');

  // ── Counsel Instructions Block ────────────────────────────────────────────
  // Omitted for 'facts' scope — procedural tasks don't need strategy notes.
  let counselBlock = '';
  if (scope !== 'facts' && instructions?.trim()) {
    counselBlock = [
      '',
      '═══════════════════════════════════════',
      'COUNSEL INSTRUCTIONS & STRATEGY NOTES',
      '═══════════════════════════════════════',
      instructions.trim(),
      '',
    ].join('\n');
  }

  // ── Inherited Matter Summary Block (Phase 4) ──────────────────────────────
  // Omitted for 'facts' scope — procedural engines don't need it. Injected
  // after counselBlock so it reads as a final, high-priority brief once the
  // AI already has the facts and counsel's strategy notes in hand.
  let inheritanceBlock = '';
  if (scope !== 'facts' && activeCase?.inheritance_data) {
    const inh = activeCase.inheritance_data;
    const lines: string[] = [
      '',
      '═══════════════════════════════════════',
      'INHERITED MATTER — FORENSIC AUDIT SUMMARY',
      '═══════════════════════════════════════',
    ];

    if (activeCase.prior_counsel_name) lines.push(`Prior Counsel: ${activeCase.prior_counsel_name}`);
    if (activeCase.handoff_stage)      lines.push(`Stage at Handoff: ${activeCase.handoff_stage}`);
    lines.push(`Audit Date: ${inh._auditDate}`);
    lines.push('');

    if (inh.inheritance_package?.current_posture) {
      lines.push('CURRENT POSTURE:');
      lines.push(inh.inheritance_package.current_posture);
      lines.push('');
    }

    if (inh.risk_register?.length) {
      lines.push('KEY RISKS:');
      inh.risk_register.forEach(r => lines.push(`• [${r.severity}] ${r.risk}`));
      lines.push('');
    }

    if (inh.inheritance_package?.immediate_actions?.length) {
      lines.push('IMMEDIATE ACTIONS:');
      inh.inheritance_package.immediate_actions.forEach(a => lines.push(`• ${a}`));
      lines.push('');
    }

    lines.push('GAP SUMMARY:');
    lines.push(
      `Errors made: ${inh.gap_report?.errors_made?.length ?? 0} | ` +
      `Cannot be recovered: ${inh.gap_report?.too_late?.length ?? 0} | ` +
      `Can be saved: ${inh.gap_report?.can_be_saved?.length ?? 0}`
    );
    lines.push('');

    inheritanceBlock = lines.join('\n');
  }

  return {
    hasIntel,
    intelBlock,
    counselBlock,
    fullContext: intelBlock + counselBlock + inheritanceBlock,
    raw: intel,
  };
}
