/**
 * AFS Legal OS — Contract Engine Types
 *
 * Kept in its own module, same pattern as src/matrimonial/types.ts and
 * src/law/registry.ts — domain-specific shapes live next to the domain,
 * not crammed into src/types/index.ts.
 *
 * Roadmap ref: 1b (Contract Engine — Foundation)
 */

// ─────────────────────────────────────────────────────────────────────────────
// CLIENT POSITION PROFILE
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Captures the client's negotiating position for a contract matter — who
 * they are in the deal, how hard to push, what can't move, what can be
 * traded. Written by the 2a capture form, read by 2c (clause register
 * generation) and 2f (missing-profile warning banner).
 *
 * Keyed by `contract_id`, NOT `case_id` — the Contract Engine is a new
 * top-level dashboard entry point (5a), not nested inside an existing
 * Case record. `contract_id` is generated when Draft/Review/Negotiate
 * mode starts and is shared by this profile and every `contract_clauses`
 * row for the same matter (see 1c).
 *
 * No schema for this table existed anywhere in the project files or the
 * uploaded bundle prior to 1b — this interface IS the schema going
 * forward. Treat it as the source of truth; edit here first if the shape
 * needs to change, then propagate to the D1 migration.
 */
export interface ClientPositionProfile {
  id:          string;
  contract_id: string;

  /** Which side of the deal the client sits on — e.g. "Lessor", "Employer", "Buyer" */
  client_role: string;

  /** How hard counsel should push in drafting/negotiation */
  risk_posture: 'conservative' | 'balanced' | 'aggressive';

  /** Ranked, most important first */
  priorities: string[];

  /** Non-negotiables */
  deal_breakers: string[];

  /** Things the client is willing to trade away */
  concessions_available: string[];

  /** Free text — background/facts about the deal */
  commercial_context: string;

  /** Any existing relationship with the counterparty */
  prior_relationship: string;

  /**
   * Feeds Pass 0 (2b) as the starting hint for candidate jurisdiction.
   * Whole-contract, not per-clause — per the 1a decision.
   * Shape matches the post-1e library convention: {COUNTRY} or
   * {COUNTRY}-{STATE}, e.g. "NG" or "NG-LA".
   */
  jurisdiction_preference?: string;

  /** Free text — counsel notes */
  special_instructions: string;

  created_at: string;
  updated_at: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// CONTRACT CLAUSES
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Knowledge-tier tag — set by 2d (Draft Mode) after each clause from 2c is
 * checked against the library. Null until 2d has run.
 */
export type KnowledgeTier =
  | 'STATUTORY_LIBRARY'   // grounded in a library-retrieved authority
  | 'GENERAL_KNOWLEDGE'   // standard drafting practice, no library hit needed
  | 'RESEARCH_NEEDED';    // library was silent — 2e generates the research checklist

/**
 * Flag tier — set by 2f (Flagging pass). Distinct from KnowledgeTier:
 * KnowledgeTier says how the clause's content was sourced; FlagTier says
 * how binding it is on the client relative to the Client Position Profile.
 */
export type FlagTier =
  | 'STATUTORY'          // mandatory — statute leaves no room to vary
  | 'GENERAL_PRUDENCE'   // standard practice, could be varied on instruction
  | 'CLIENT_INSTRUCTION'; // driven directly by client_position_profile fields

/**
 * Per-authority-type research query, generated by 2e for any clause tagged
 * RESEARCH_NEEDED. Standalone/testable independent of 2d per the roadmap.
 */
export interface ResearchNeededQuery {
  authority_type: 'statute' | 'common_law' | 'regulator' | 'sector_trigger' | 'case_law_trend';
  query:          string;
}

/**
 * One round of negotiation history for a clause — appended by 4a on every
 * round change. Never mutated after being written; append-only, oldest first.
 */
export interface ClauseHistoryEntry {
  round_number: number;
  clause_text:  string;
  changed_at:   string;
  changed_by:   'draft' | 'review' | 'negotiate';
  note?:        string;   // e.g. what changed and why, for negotiate-mode diffs
}

/**
 * One clause of a contract. Rows share `contract_id` with the
 * ClientPositionProfile for the same matter (1b).
 *
 * `jurisdiction` is DENORMALIZED onto every row per the 1a decision
 * (whole-contract, not per-clause) — copied from the contract-level
 * resolution at generation time so 2d's library filter
 * (`filter: { jurisdiction }`) is a flat per-clause read, no join needed.
 * Every clause in a given contract_id will carry the same value; that
 * repetition is intentional, not a normalization bug.
 *
 * `round_number` and `history` exist here (not added later) because 4a
 * ("Negotiate Mode — round-tracking") is explicitly documented in the
 * roadmap as reusing this schema rather than migrating it.
 */
export interface ContractClause {
  id:          string;
  contract_id: string;

  clause_number: string;   // e.g. "3.2"
  clause_text:   string;

  /** Denormalized whole-contract value — see doc comment above. */
  jurisdiction: string;

  /** Null until 2d has run for this clause. */
  knowledge_tier?: KnowledgeTier | null;

  /** Null until 2f has run for this clause. */
  flag_tier?: FlagTier | null;

  /** Present only when knowledge_tier === 'RESEARCH_NEEDED'. Set by 2e. */
  research_needed?: ResearchNeededQuery[];

  /** Negotiate Mode (4a) — increments per round; append to history on change. */
  round_number: number;
  history:      ClauseHistoryEntry[];

  created_at: string;
  updated_at: string;
}
